// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/proto/serverPush.proto

package com.myob.serverpush.api;

public interface PushResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serverpush.PushResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
