// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/proto/serverPush.proto

package com.myob.serverpush.api;

public interface PushRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serverpush.PushRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
